---
title: 20181102 异常
date: 2018-11-2
tags: [Java]
---

# 20181102异常

#### 1  异常的概念—分类

##### 1.1 异常的概念

**异常**（Exception）也叫例外，就是在程序运行过程中所发生的**不正常的的事件**，它会**中断**正在运行的程序

##### 1.2 异常的分类	 

检查时异常 --Checked异常: 程序必须处理的异常	

![1541123628534](http://www.zwer.xyz/images/%20disorder/1541123628534.png)



#### 2 异常处理的方式之捕获异常

##### 2.1 try{}catch(){}类型

![1541124143370](http://www.zwer.xyz/images/%20disorder/1541124143370.png)





​         				c. 异常类型与捕获类型不相同

![1541124198856](http://www.zwer.xyz/images/%20disorder/1541124198856.png)





##### 2.2 try{} finally{}类型

注意：退出Java虚拟机，不执行finally中的代码

##### 2.3  try{}catch{}和try{}finally{}类型

![1541124676607](http://www.zwer.xyz/images/%20disorder/1541124676607.png)



#### 3 异常处理的方式之声明异常

##### 3.1`throws`声明异常	

**方法名的后面**，用于声明该方法可能会产生一个异常如果方法声明的是 Exception 类型的异常或者是Checked `Exception`异常，要求方法的调用出必须做处理

1. 继续使用`throws`向上（方法的调用处）声明
2. 使用`try-catch-finally`进行处理

1. 父类的方法声明了Exception类型的异常，子类在重写方法时，可以声明也可以不声明。但是如果子类重写后的方法使用**super关键字调用父类的方法**，那么要求**必须**对异常进行处理
2. 如果父类的方法中没有声明异常，那么子类的方法中如果一定有Exception或Checked异常，要求子类必须使用try-catch处理，或者给父类加上异常的声明

3.如果父类的异常是`RuntimeException`,那么子类可处理也可不处理

##### 3.2throw 抛出异常对象

**方法体中**  在捕获一个异常前，必须有一段代码先生成异常对象并把它抛出，这个过程我们以手工做的，也可以由JRE实现，但是它们调用的都是throw子句



##### 3.3throws和throw区别

1. throws用于声明方法可能会产生的异常的类型

   throw 手动抛出异常对象

2. throws 写在方法名称后面

   throw用于写在 方法里


#### 4  常见异常处理

##### 4.1运行时异常

1 算术异常  `ArtemExcetion`

2 空指针异常 `NullPointerException`

3 类型转换异常 `ClassCastException`

4 数据下标越界 `ArrayIndexOutOfBoundsException`

5 期望的数据类型与输入的数据类型不相匹配`InputMisMatchException`

```java
package cn.szxy.exception;

import java.util.Arrays;
import java.util.Scanner;

public class CommonAbnormal {
	public static void main(String[] args) {
		
		
		//1. 算术异常   ArithmeticException
		int a = 10;
		int b =0;
		if(b ==0 ){
			System.out.println("除数不能为0");
		}else{
			int c = a/b;
			System.out.println("c="+c);
		}
		
		//2. 空指针异常 
		String s = null;
		if(s==null){
			System.out.println("空指针");
		}else{
			System.out.println(s.charAt(0));
		}
		
		//3. 类型转换
		Animal d = new Dog();//向山类型转换
		if(d instanceof Cat){
			Cat c = (Cat)d;//向下类型转换，转换成真实的子类对象
		}else{
			System.out.println("类型不匹配");
		}
		
		//4.数组下标越界
		int[] arr = {1,2,3,4,5};
		int index = 4;
		if(index > arr.length-1){
			System.out.println("数组下标越界");
		}else{
			System.out.println(arr[index]+" ");
		}
		
		//5。 期望输入数据类型与输入的数据类型不匹配
		Scanner input = new Scanner(System.in);
		
		if(input.hasNextInt()){
			int num = input.nextInt();
			
			System.out.println("匹配成功 "+ num);
		}else{
			System.out.println("期望输入数据类型与输入的数据类型不匹配");
		}
	}
}	

class  Animal{
	
}
class Dog extends Animal{
	
}
class Cat extends Animal{
	
}

```

运行结果：

![1541131822768](http://www.zwer.xyz/images/%20disorder/1541131822768.png)



##### 4.2 检查时异常 Checked Exception

检查时异常，N多个程序在编译期间**必须**处理的异常

a `SQLException`

b `IOException`

c `ParseException`

```java
void TestFile(){
		// TODO Auto-generated method stub
		//super.TestFile();
		File f = new File("D:\\1.txt");
		try {
			f.createNewFile();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}
```

要求必须做处理：

1. throws 向上声明
2. try-catch-finally



#### 5 自定义异常

步骤：

1 继承`Exception `或 `RunTimeException`

2 定义构造方法

3. 使用异常

   //创建`SexEeception`异常类，并添加构造方法

   ```java
   package cn.szxy.exception.defineException;
   
   public class SexException extends Exception{
   	
   	public SexException() {//无参构造方法
   		super();
   		// TODO Auto-generated constructor stub
   	}
   	public SexException(String message) {//有参构造方法
   		super(message);
   		// TODO Auto-generated constructor stub
   	}
   	
   }
   
   ```

   //测试`SexException`异常类

```java
package cn.szxy.exception.defineException;

import java.util.Scanner;

public class TestSexException {
	public static void main(String[] args) {
		Scanner input = new Scanner(System.in);
		System.out.print("请输入性别：");
		String sex = input.nextLine();
		if(sex.equals("男")||sex.equals("女")){
			System.out.println("性别录入正确");
		}else{
			try {
				throw new SexException("请输入男或女");
			} catch (SexException e) {
				// TODO Auto-generated catch block
				//e.printStackTrace();
				System.err.println("输入有误");
			}
		}
	}
}

```

运行结果：

​			         ![1541132034543](http://www.zwer.xyz/images/%20disorder/1541132034543.png)



![1541131988844](http://www.zwer.xyz/images/%20disorder/1541131988844.png)







